## importing required libraries

In [ ]:
import numpy as np
import pandas as pd

**1.  Generate an array of zeroes using inbuilt numpy function.**

In [ ]:
print( np.zeros( (1,8),dtype=int ) )

[[0 0 0 0 0 0 0 0]]


**2. Run the given code and find the dot product of both arrays.**

In [ ]:

import numpy as np
a = np.random.randint(2,10, (3,4))
b = np.random.randint(2,10, (4,3))
print(a)
print(b)

[[4 7 5 8]
 [3 5 4 3]
 [4 9 8 5]]
[[8 2 5]
 [3 3 7]
 [2 5 7]
 [8 9 7]]


In [ ]:
a.dot(b)

array([[148, 168, 178],
       [100, 109, 143],
       [121, 133, 139]])

**3. Read the csv file provided using pandas and display the first 5 entries**

In [ ]:
data =pd.read_csv('/content/data.csv')
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

**4. Describe the data with all features.**

In [ ]:
data.describe()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800

**Find the total count of missing values for each feature.**

In [ ]:
data.describe().isnull().count()

OBJECTID      8
ACRES         8
SHAPE.AREA    8
SHAPE.LEN     8
dtype: int64

**6. Display all the unique values from the 'DESCRIPTION’ column.**

In [ ]:
data.DESCRIPTION.unique()

array(['State Park', 'Interpretive Center', 'State Recreation Area',
       'State Natural Area', 'State Nature Preserve'], dtype=object)

**7. Create a grouped table usin 'DESCRIPTION' as the grouping columns with the means of all the other columns.**

In [ ]:
data.groupby('DESCRIPTION').mean()

OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135

**Generate a random sample of 10 rows from the data.**

In [ ]:
data.sample(10)

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
24        42         Pelican Point State Recreation Area  ...   0.000013   0.026357
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487
5         26                        Icelandic State Park  ...   0.000461   0.166712
6         27                   Lake Metigoshe State Park  ...   0.000751   0.212196
12        35        Butte St. Paul State Recreation Area  ...   0.000025   0.022095
9         30           Fort Mandan State Recreation Area  ...   0.000005   0.009396
20        41           Missouri River State Natural Area  ...   0.000083   0.087192
11        32                      Sully Creek State Park  ...   0.000030   0.024016

[10 rows x 6 columns]

**9. Add a Feature called 'New_feature' to the new Dataset and Add Random float Values in between 0 and 1 using Numpy.**

In [ ]:
new_feature= np.random.rand(25,1)
data['new_feature']=new_feature
data.head()

OBJECTID                        UNIT_NAME  ... SHAPE.LEN  new_feature
0        21        Fort Stevenson State Park  ...  0.135641     0.049869
1        22           Beaver Lake State Park  ...  0.080067     0.848436
2        23  Fort Abraham Lincoln State Park  ...  0.119868     0.877442
3        24           Fort Ransom State Park  ...  0.128733     0.569155
4        25        Grahams Island State Park  ...  0.125546     0.754170

[5 rows x 7 columns]

**10. Replace zero value of column 'OBJECTID' with mean value permanently.**

In [ ]:
mean_value=data.OBJECTID.mean()

data[pd.isnull(data.OBJECTID)]
data.OBJECTID.fillna(mean_value)



0     21
1     22
2     23
3     24
4     25
5     26
6     27
7     28
8     29
9     30
10    31
11    32
12    35
13    36
14    33
15    34
16    37
17    38
18    39
19    40
20    41
21    43
22    44
23    45
24    42
Name: OBJECTID, dtype: int64